development:
  clients:
    default:
      use_utc: true
      database: development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      use_utc: true
      database: test
      hosts:
        - localhost:27017
